services:
  identity-auth:
    build: ./identity-auth-service

  registration:
    build: ./registration-verification-service

  organization:
    build: ./organization-tenant-service

  notification:
    build: ./notification-service