"""Add organization_id to users

Revision ID: f10af7b9c8b7
Revises: cd00d50aedde
Create Date: 2026-07-31 18:39:25.969441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10af7b9c8b7'
down_revision: Union[str, Sequence[str], None] = 'cd00d50aedde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'organization_id')
    # ### end Alembic commands ###
